# Dimentions


WINDOW_RATIO = [9, 16]
WINDOW_HEIGHT = 720

WINDOW_WIDTH = int(round(WINDOW_HEIGHT / WINDOW_RATIO[1] * WINDOW_RATIO[0]))
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
WINDOW_CENTER_X = int(round(WINDOW_WIDTH / 2))
WINDOW_CENTER_Y = int(round(WINDOW_HEIGHT / 2))
WINDOW_CENTER = (WINDOW_CENTER_X, WINDOW_CENTER_Y)


# Animations


BACKGROUND_SCROLL_SPEED = 20


# Colors


COLOR_BASE = (100, 200, 255)